# URLs
permalink: pretty
baseurl: /dhamma

# Structure configuration
source: ./
destination: ./_site

# Site settings
title: 'Dhamma'
description: 'A Collection of Dhamma (Chants & Pāḷi)'
url: https://job-talk.github.io

# Markdown
markdown: kramdown

exclude:
  - .gitignore
  - LICENSE
  - README.md
  - todo.txt
  - Gemfile

gems:
  - jekyll-sitemap
