# URLs
permalink: pretty
baseurl: /dhamma

# Structure configuration
source: ./
destination: ./_site

# Site settings
title: 'Dhamma'
description: 'A Collection of Dhamma (Chants & Pāḷi)'
url: https://job-talk.github.io

# Markdown
markdown: kramdown

exclude:
  - .gitignore
  - LICENSE
  - README.md
  - todo.txt
  - Gemfile

gems:
  - jekyll-sitemap
  - jekyll-assets

assets:
  compress:
    css: true
    js: true

  #

  autowrite: true
  cache: default
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #

  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"

  #

  sources:
    - assets/css
    - assets/images
    - assets/js

  #

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true
