# URLs
permalink: pretty
baseurl:

# Structure configuration
source: ./
destination: ./_site

# Site settings
title: 'Dhammapuja'
description: 'A Karaoke for Chanting Dhamma in English and Pāli'
url: https://dhammapuja.com

# Markdown
markdown: kramdown

exclude:
  - .gitignore
  - LICENSE
  - README.md
  - todo.txt
  - Gemfile

plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

assets:
  compress:
    css: true
    js: true

  #

  autowrite: true
  cache: default
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #

  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"

  #

  sources:
    - assets/css
    - assets/_sass
    - assets/img
    - assets/js
    - assets/audio

  #

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true

seo:
  title: 'Dhammapuja'
  description: 'A Karaoke for Chanting Dhamma in English and Pāli'
  url: https://dhammapuja.com/
